version: 2.1
jobs:
  logipedia_build:
    docker:
      - image: ocaml/opam2:alpine
    steps:
      - run: sudo apk add m4 git git-lfs openssh
      - run:
          name: opam_deps
          command: |
            opam switch 4.07
            opam update
            opam pin add dedukti git+https://github.com/Deducteam/Dedukti.git -qy
            opam install dune yojson ppx_deriving_yojson
      - checkout
      - run: git lfs pull
      - run: eval $(opam env) && make dedukti

  json_exp:
    docker:
      - image: ocaml/opam2:alpine
    steps:
      - run: sudo apk add m4 git git-lfs openssh
      - run:
          name: opam_deps
          command: |
            opam switch 4.07
            opam update
            opam pin add dedukti git+https://github.com/Deducteam/Dedukti.git -qy
            opam install dune yojson ppx_deriving_yojson
      - checkout
      - run: git lfs pull
      - run: eval $(opam env) && make json
      - run: [[ $(ls -l export/json/ | wc -l) -ne 0 ]]

workflows:
  version: 2.1
  build:
    jobs:
      - logipedia_build
      - json_exp
