 version: 2.1
 jobs:
   ddk_type_check:
     docker:
       - image: ocaml/opam2:alpine
     steps:
       - run: sudo apk add m4
       - run:
           name: opam_deps
           command: |
             opam update
             opam install --deps-only dedukti
       - run:
           name: dk_install
           command: |
             eval $(opam env)
             git clone https://github.com/Deducteam/Dedukti.git
             cd Dedukti
             make
             make install
       - checkout
       - run: make

 workflows:
  version: 2.1
  build:
    jobs:
      - ddk_type_check
