version: 2.1
jobs:
  logipedia_build:
    docker:
      - image: ocaml/opam2:alpine
    steps:
      - run: sudo apk add m4 git git-lfs ssh
      - run:
          name: opam_deps
          command: |
            opam switch 4.07
            opam update
            opam pin add dedukti git+https://github.com/Deducteam/Dedukti.git -qy
            opam install dune yojson ppx_deriving_yojson
            eval $(opam env)
      - checkout
      - run: make dedukti

  json_exp:
    docker:
      - image: ocaml/opam2:alpine
    steps:
      - run: sudo apk add m4 git git-lfs ssh
      - run:
          name: opam_deps
          command: |
            opam switch 4.07
            opam update
            opam pin add dedukti git+https://github.com/Deducteam/Dedukti.git -qy
            opam install dune yojson ppx_deriving_yojson
            eval $(opam env)
      - checkout
      - run: make json

workflows:
  version: 2.1
  build:
    jobs:
      - logipedia_build
      - json_exp
