version: 2.0
jobs:
  build_logipedia:
    docker:
      - image: ocaml/opam2:alpine
    steps:
      - run: sudo apk add m4 git git-lfs openssh
      - run:
          name: opam_deps
          command: |
            opam switch 4.07
            opam update
            opam pin add dedukti git+https://github.com/Deducteam/Dedukti.git -qy
            opam install dune yojson ppx_deriving_yojson
      - checkout
      - run: git lfs pull
      - run: eval $(opam env) && make dedukti

  json_export:
    docker:
      - image: ocaml/opam2:alpine
    steps:
      - run: sudo apk add m4 git git-lfs openssh
      - run:
          name: opam_deps
          command: |
            opam switch 4.07
            opam update
            opam pin add dedukti git+https://github.com/Deducteam/Dedukti.git -qy
            opam install dune yojson ppx_deriving_yojson
      - checkout
      - run: git lfs pull
      - run: eval $(opam env) && make json
      - run: cp -r export/json /tmp
      - store_artifacts:
          path: /tmp/json
      - persist_to_workspace:
          root: /tmp
          paths: 
            - json

  build_website:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: pip install --user ./logigen
      - run: logigen -i /tmp/workspace/json
      - run: cp -r gen_website /tmp/
      - store_artifacts:
          path: /tmp/gen_website


workflows:
  version: 2.1
  build:
    jobs:
      - build_logipedia
      - json_export
      - build_website:
          requires:
            - json_export
