 version: 2.1
 jobs:
   ddk_type_check:
     docker:
       - image: ocaml/opam2:ubuntu-18.04-ocaml-4.05
     steps:
       - checkout
       - run: sudo apt-get install -qy build-essential m4 unzip git time zip
       - run: opam update
       - run: opam pin add dedukti git+https://github.com/Deducteam/Dedukti.git -qy
       - run: git clone https://github.com/Deducteam/Dedukti.git && cd Dedukti && make && make install
       - run: opam install coq
       - run: eval $(opam env)
       - run: make coq

 workflows:
  version: 2.1
  build:
    jobs:
      - ddk_type_check
