;; Augmented BNF reprensenting the information on a web page
;; <ppterm> defined in an auxiliary file

<name> = *<mod> SP <id>
;; Fully qualified name of the object

<logic> = "coq" / "matita" / ...
;; The available logic systems

<from> = <logic>
;; The logic from which the object comes from

<taxonomy> = "axiom" / "proof" / "definition" / "constant"
;; The category of the object

<ttype> = <ppterm>
;; Statement

<body> = <ppterm>
;; Body if definition

<dependency> = <name> SP <taxonomy>
;; A single dependency

<theory> = *(<dependency>)
;; A list of dependencies composing the theory

<to> = *<logic>
;; The available logics to which the object has been exported

<general> = <name> CR
            *<from> CR
            <taxonomy> CR
            <ttype> CR
            *<dependency> CR
            <theory> CR
            <to>
;; Content of the general section

<export> = <logic> CR ; the exported logic
           <path> CR ; path of files to be downloaded
           [ *ALPHA ] CR ; statement in the foreign logic
;; Export section

<main> = <general> CR *<export>
;; Entry point of the web page
