;; Augmented BNF reprensenting the information on a web page
;; <ppterm> defined in an auxiliary file

;; / is the alternative
;; SP is for an explicit space
;; quantification is prefix i.e. *ALPHA for any number of characters
;; [ x ] is the option

<id>     = ("_" / ALPHA) *(ALPHA / DIGIT)
;; An identifer

<qid> = *(<id> ".") <id>
;; Fully qualified name of the object, must be unique

<logic> = "coq" / "matita" / ...
;; The available logic systems

<from> = <logic>
;; The logic from which the object comes from

<taxonomy> = "axiom" / "proof" / "definition" / "constant"
;; The category of the object

<dependency> = <name> SP <taxonomy>
;; A single dependency

<general> = <qid> CR
            <logic> CR       ; logic of origin
            <taxonomy> CR
            <ppterm> CR      ; statement
            [ <ppterm> ] CR  ; body
            *<dependency> CR ; dependencies
            *<theory> CR     ; theory
            *<logic>         ; available exports
;; Content of the general section

<export> = <logic> CR    ; the exported logic
           <path> CR     ; path of files to be downloaded
           [ *ALPHA ] CR ; statement in the foreign logic
;; Export section

<main> = <general> CR *<export>
;; Entry point of the web page
