;; Mappings from ctpicef to latex symbols
(( "cic:ctpicef/S.axm"    . "\\mathfrak{S}" )
 ( "cic:ctpicef/T.axm"    . "\\mathfrak{T}" )
 ( "cic:ctpicef/Bool.axm" . "\\mathbb{B}"   )
 ( "cic:ctpicef/eps.axm"  . "\\espilon"     )
 ( "cic:ctpicef/true.axm" . "\\top"         )
 ( "cic:ctpicef/prop.axm" . "\\mathbb{P}"   )
 ( "cic:ctpicef/set.axm"  . "\\mathbb{S}"   )
 ( "cic:ctpicef/s.axm"    . "\\mathfrak{s}" )
 ( "cic:ctpicef/u.axm"    . "\\mathfrak{u}" )
 ( "cic:Coq__Init__Logic/and.axm" . "\\wedge"          )
 ( "cic:Coq__Init__Logic/or.axm"  . "\\lor"            )
 ( "cic:Coq__Init__Logic/iff.def" . "\\leftrightarrow" ))
